### ISSUE TITLE
More Filters

### ISSUE THREAD

**Issue by abhi06991** [pixolith/fabricjs-color-matrix-filter#1]
Hi..I just love this extension. But you have not mentioned how to create other filters. Just three filters have been provided in your example. What would be matrix values for creating many more filters?

**Comment by MDSLKTR** [comment]
Hey man, thank you for the kind words! You can pretty much configure anything you like at this point. This page explains it fairly good: http://www.webwasp.co.uk/tutorials/219/Color_Matrix_Filter.php. My example matrixes have been taken from: http://phoboslab.org/log/2013/11/fast-image-filters-with-webgl. So you can basicly put in any Color Matrix you want.

Regards,
Simon
