### ISSUE TITLE
Applying filter to background image

### ISSUE THREAD

**Issue by davidrossiter** [pixolith/fabricjs-color-matrix-filter#2]
Another fantastic fabricjs resource Simon :) thanks for creating this! 

I am having trouble working how to apply the filters to the background image of the canvas only, instead of an image object. I tried something based off your example page but I can't get it working.

Is it even possible?

I put together a stripped down test page: http://jsbin.com/qixehudono/1/edit?html,js,output

**Comment by MDSLKTR** [comment]
Hey there :),

i don't think it is. What you can do though is use a normal fabric image object, apply the filters there and then do `canvas.backgroundImage = imageObject.getElement();`

See this example where it is used on an overlayImage:
http://stackoverflow.com/questions/13538460/where-is-a-way-to-apply-a-filter-in-the-overlayimage/13541734#13541734

should be same thing for the backgroundImage.

Regards,
Simon
