### ISSUE TITLE
Retina screen problem (and fix)

### ISSUE THREAD

**Issue by stufreen** [pixolith/fabricjs-color-matrix-filter#3]
First let me say I really like this filter. It's fast, and it let me roll several different filters (brightness, contrast, color manipulation, black and white, etc.) into one.

I had an issue with retina screens though. The filter only applied to the top left quadrant of the canvas.

It seems the issue was that the filter uses "canvasEl.width" and "canvasEl.height" on line 30 of colorMatrixFilter.js. This seems to give the DOM width and height, rather than the actual pixel-level width and height. I fixed it easily on my project by replacing line 30 as follows:

`imageData = context.getImageData( 0, 0, canvasEl.width * window.devicePixelRatio, canvasEl.height * window.devicePixelRatio ),`

**Comment by MDSLKTR** [comment]
Hey there,

thank you for your feedback, updates can be made :). I thought fabric would handle this for you but maybe i was wrong. Did you try to use setDimensions on the your canvas with the same formula? 

for example:

canvas.setDimensions(800 \* window.devicePixelRatio, 600 \* window.devicePixelRatio);

Afaik the filter will only read from the given canvas dimensions.

Regards,
Simon

**Comment by stufreen** [comment]
In my case, to get the canvas to look sharp on retina screens I was setting dimensions 4x as big as I needed it to be, and then shrinking it down with css "transform: scale(0.5)".

I think the issue is that JavaScript gets the width of DOM elements _before_ taking devicePixelRatio into account. A fabric canvas that you do a canvas.setDimensions(800, 600) to will appear as 800x600 in the DOM. However on a retina screen that canvas actually has 1600x1200 real pixels.
