### ISSUE TITLE
Integrating in fabricjs

### ISSUE THREAD

**Issue by asturur** [pixolith/fabricjs-color-matrix-filter#4]
Do you mind if i pull it in the official fabricjs library?

**Comment by MDSLKTR** [comment]
Not at all. I can make an official PR if you like :). Very nice.

**Comment by MDSLKTR** [comment]
For Reference: https://github.com/kangax/fabric.js/pull/3139

**Comment by asturur** [comment]
thanks, as soon as i get notebook i ll merge it.
